import React from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';
import { motion } from 'motion/react';

interface RefundPolicyProps {
  onBack: () => void;
}

export default function RefundPolicy({ onBack }: RefundPolicyProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.4 }}
      className="pt-32 pb-24 px-6 min-h-[80vh] bg-slate-50"
    >
      <div className="max-w-4xl mx-auto bg-white p-10 md:p-16 rounded-[3rem] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.05)] border border-slate-100">

        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm font-black text-brand-accent hover:text-brand-accent-hover transition-colors uppercase tracking-widest mb-10"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </button>

        <div className="flex items-center gap-4 mb-10">
          <div className="w-16 h-16 bg-brand-accent rounded-[1.5rem] flex items-center justify-center shadow-xl shadow-brand-accent/20">
            <ShieldCheck className="text-white w-8 h-8" />
          </div>
          <div>
            <h1 className="text-4xl md:text-5xl font-black text-slate-900 tracking-tighter">
              Refund Policy
            </h1>
            <p className="text-slate-400 font-bold text-sm uppercase tracking-widest mt-2">
              Last Updated: January 1, 2025
            </p>
          </div>
        </div>

        <div className="prose prose-slate prose-lg max-w-none text-slate-600 space-y-8">

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">1. Policy Scope</h2>
            <p>
              <strong>1.1</strong> This Refund Policy applies to all purchases made through Logistics VIN Report for digital vehicle history report services.
            </p>
            <p>
              <strong>1.2</strong> This policy should be read in conjunction with our Terms & Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">2. Nature of Service</h2>
            <p>
              <strong>2.1</strong> Logistics VIN Report provides digital services delivered electronically.
            </p>
            <p>
              <strong>2.2</strong> No physical goods are shipped or delivered.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">3. Completion of Delivery</h2>
            <p><strong>3.1</strong> Delivery of the service is deemed complete when:</p>
            <ul className="list-[lower-alpha] pl-6 space-y-2 mt-4">
              <li>the vehicle history report is generated by our system, and</li>
              <li>access to the report is provided to the customer via electronic means, including a secure dashboard, secure access link, or email notification.</li>
            </ul>
            <p className="mt-4">
              <strong>3.2</strong> Delivery is considered complete regardless of whether the customer opens, views, or downloads the report after access is provided.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">4. Refund Eligibility</h2>
            <p>
              <strong>4.1</strong> Because the service is digital and delivered electronically, all sales are final and non-refundable once delivery is complete, except where required by applicable law.
            </p>
            <p><strong>4.2</strong> Refunds may be considered only under the following limited circumstances:</p>
            <ul className="list-[lower-alpha] pl-6 space-y-2 mt-4">
              <li>the report could not be generated due to a system error attributable to Logistics VIN Report;</li>
              <li>a technical issue prevented access to the report and could not be resolved;</li>
              <li>the delivered report does not correspond to the selected service tier.</li>
            </ul>
            <p className="mt-4">
              <strong>4.3</strong> Refund approval is at the sole discretion of Logistics VIN Report and subject to verification.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">5. Non-Refundable Situations</h2>
            <p><strong>5.1</strong> Refunds will not be issued for:</p>
            <ul className="list-[lower-alpha] pl-6 space-y-2 mt-4">
              <li>dissatisfaction with report contents when the report was successfully delivered;</li>
              <li>claims that the report was not opened or downloaded after access was provided;</li>
              <li>changes of mind after purchase;</li>
              <li>limitations in data availability from third-party sources disclosed in our Terms & Conditions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">6. Refund Request Procedure</h2>
            <p>
              <strong>6.1</strong> Refund requests must be submitted within <strong>7 days</strong> of purchase.
            </p>
            <p><strong>6.2</strong> The customer must provide:</p>
            <ul className="list-[lower-alpha] pl-6 space-y-2 mt-4">
              <li>order number;</li>
              <li>VIN;</li>
              <li>a brief explanation of the issue.</li>
            </ul>
            <p className="mt-4">
              <strong>6.3</strong> Failure to provide the required information may result in denial of the refund request.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">7. Refund Processing</h2>
            <p>
              <strong>7.1</strong> Approved refunds will be issued to the original payment method only.
            </p>
            <p>
              <strong>7.2</strong> Processing times may vary by financial institution but generally occur within <strong>3–7 business days</strong>.
            </p>
            <p>
              <strong>7.3</strong> Any non-refundable processing fees, where applicable, will not be returned.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">8. Abuse & Fraud Prevention</h2>
            <p>
              <strong>8.1</strong> Logistics VIN Report reserves the right to deny refund requests where abuse, misuse, or fraudulent activity is suspected.
            </p>
            <p>
              <strong>8.2</strong> Repeated refund requests may result in account restrictions or refusal of future service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">9. Contact Information</h2>
            <p><strong>9.1</strong> Refund-related inquiries should be directed to:</p>
            <p className="mt-4">
              <strong>Email:</strong> trustedvinreport@gmail.com
              <br />
              <strong>Subject Line:</strong> Refund Request – Order #[Order Number]
            </p>
          </section>

        </div>
      </div>
    </motion.div>
  );
}
