import React from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';
import { motion } from 'motion/react';

interface TermsAndConditionsProps {
  onBack: () => void;
}

export default function TermsAndConditions({ onBack }: TermsAndConditionsProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.4 }}
      className="pt-32 pb-24 px-6 min-h-[80vh] bg-slate-50"
    >
      <div className="max-w-4xl mx-auto bg-white p-10 md:p-16 rounded-[3rem] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.05)] border border-slate-100">
        
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm font-black text-brand-accent hover:text-brand-accent-hover transition-colors uppercase tracking-widest mb-10"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </button>

        <div className="flex items-center gap-4 mb-10">
          <div className="w-16 h-16 bg-brand-accent rounded-[1.5rem] flex items-center justify-center shadow-xl shadow-brand-accent/20">
            <ShieldCheck className="text-white w-8 h-8" />
          </div>
          <div>
            <h1 className="text-4xl md:text-5xl font-black text-slate-900 tracking-tighter">
              Terms & Conditions
            </h1>
            <p className="text-slate-400 font-bold text-sm uppercase tracking-widest mt-2">
              Last Updated: January 1, 2025
            </p>
          </div>
        </div>

        <div className="prose prose-slate prose-lg max-w-none text-slate-600 space-y-8">
          
          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the services provided by VinTrustReport, you confirm that you have read, understood, and agreed to be bound by these Terms & Conditions. If you do not agree with these Terms & Conditions, you must not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">2. Nature of Service</h2>
            <p>VinTrustReport provides digital vehicle history report services only.</p>
            <p>All reports are generated and delivered electronically. No physical goods are shipped.</p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">3. Service Description</h2>
            <p>
              Vehicle history reports are compiled using data obtained from publicly available records and authorized third-party sources, which may include:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>NMVTIS databases</li>
              <li>Insurance records</li>
              <li>Auto auctions</li>
              <li>Manufacturers and other industry sources</li>
            </ul>
            <p className="mt-4">
              Reports are provided for informational purposes only and are intended to assist customers in making vehicle-related decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">4. Digital Delivery & Completion of Service</h2>
            <p>Delivery of the service is deemed complete when both of the following occur:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>The vehicle history report is generated by our system; and</li>
              <li>Access to the report is provided to the customer through electronic means, including any of the following:
                <ul className="list-circle pl-6 space-y-1 mt-2">
                  <li>Secure dashboard access</li>
                  <li>Secure access link</li>
                  <li>Email notification</li>
                </ul>
              </li>
            </ul>
            <p className="mt-4">
              Delivery is considered complete regardless of whether the customer opens, views, or downloads the report after access is provided.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">5. Access & Availability</h2>
            <p>
              Customers are responsible for providing accurate contact information and maintaining the ability to access digital content.
            </p>
            <p>VinTrustReport is not responsible for delivery issues caused by:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Incorrect email addresses</li>
              <li>Spam or junk-mail filtering</li>
              <li>Customer-side technical limitations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">6. Data Accuracy & Limitations</h2>
            <p>
              While reasonable efforts are made to ensure accuracy, VinTrustReport does not guarantee the completeness, accuracy, or timeliness of report data.
            </p>
            <p>
              Vehicle history data may be incomplete, delayed, or unavailable due to limitations of third-party data sources.
            </p>
            <p>
              Reports are provided "as is", without warranties of any kind, express or implied.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">7. Permitted Use</h2>
            <p>Reports may be used only for lawful and legitimate purposes, including:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Vehicle purchase evaluation</li>
              <li>Insurance or underwriting review</li>
              <li>Business or fleet analysis</li>
              <li>Legal reference where applicable</li>
            </ul>
            <p className="mt-4">
              Reports may not be used for unlawful, deceptive, or harmful activities.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">8. Prohibited Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Resell, redistribute, or reproduce reports without authorization;</li>
              <li>Attempt to reverse engineer or manipulate our systems;</li>
              <li>Access the service using automated tools without permission;</li>
              <li>Misuse reports for harassment, fraud, or illegal activity.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">9. Payment Terms</h2>
            <p>All payments must be made in full at the time of purchase.</p>
            <p>Prices are displayed prior to checkout and may change without notice.</p>
            <p>
              Payments are processed via secure third-party payment processors. VinTrustReport does not store full payment card details.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">10. Refunds</h2>
            <p>
              Because the service is digital and delivered electronically, all sales are final and non-refundable once delivery is complete, except where required by applicable law.
            </p>
            <p>
              Delivery completion is defined in Clauses 4.1–4.2 of these Terms & Conditions.
            </p>
            <p>
              Refund eligibility and limitations are further detailed in the Refund Policy, which forms an integral part of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, VinTrustReport's total liability shall be limited to the amount paid for the specific report giving rise to the claim.
            </p>
            <p>
              VinTrustReport shall not be liable for indirect, incidental, consequential, or special damages arising from use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">12. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless VinTrustReport from any claims, losses, liabilities, or expenses arising from misuse of the service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">13. Governing Law & Jurisdiction</h2>
            <p>
              These Terms & Conditions are governed by the laws of the State of Texas, United States.
            </p>
            <p>
              Any disputes shall be subject to the exclusive jurisdiction of the courts located in Travis County, Texas.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">14. Modifications to Terms</h2>
            <p>VinTrustReport reserves the right to modify these Terms & Conditions at any time.</p>
            <p>
              Continued use of the service following updates constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-black text-slate-900 mb-4">15. Contact Information</h2>
            <p>
              For questions regarding these Terms & Conditions, please contact:
              <br />
              <strong>Email:</strong> info@worldvinreport.com
            </p>
          </section>

        </div>
      </div>
    </motion.div>
  );
}
